### ISSUE TITLE
Cannot execute AppImage (Debian 64-bit)

### ISSUE THREAD

**Issue by jones137** [FWGS/xash3d-deploy#3]
> $ ./Xash3DFWGS-i386.AppImage
Xash3D FWGS installed as AppImage.
/tmp/.mount_Xash3Dc3Mla7/AppRun: 6: [: unexpected operator
/tmp/.mount_Xash3Dc3Mla7/AppRun: 11: /tmp/.mount_Xash3Dc3Mla7/AppRun: /tmp/.mount_Xash3Dc3Mla7/xash3d: not found

script syntax mistake?

**Comment by jones137** [comment]
After the update the script syntax seems fixed but I can't launch it anyway:

> $ ./Xash3DFWGS-i386.AppImage 
Xash3D FWGS installed as AppImage.
/tmp/.mount_Xash3DtSssd8/AppRun: 11: /tmp/.mount_Xash3DtSssd8/AppRun: /tmp/.mount_Xash3DtSssd8/xash3d: not found

**Comment by mittorn** [comment]
Do you have required ldso /lib/ld-linux.so.2?

**Comment by jones137** [comment]
Can you please point me in the direction what Debian package contains this lib?

**Comment by jones137** [comment]
Yes, I do have it in both /lib and /lib32, and I have also /lib64/ld-linux-x86-64.so.2

**Comment by jones137** [comment]
The new version didn't give me the error and asked for "valve" directory, so I copied it to appimage's location and re-run, however it just says on the command line

> type 'map <mapname>' to run server... (TAB-autocomplete is working too)

and nothing else happens, no GUI launches or anything.

**Comment by mittorn** [comment]
gui needs x11 and opengl libraries in multilib

**Comment by probonopd** [comment]
It is because this is a 32-bit rather than a 64-bit binary; why?

```
me@host:~$ file Downloads/Xash3DFWGS-i386.AppImage 
Downloads/Xash3DFWGS-i386.AppImage: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.2, for GNU/Linux 2.6.18, stripped
```

Please provide a 64-bit one, too.

**Comment by mittorn** [comment]
install libgl1-mesa-glx or build 64-bit binary and game libraries manually. Valve does not provide 64-bit client libraries and 64 bit server is deprecated for many years. And not compatible with aslr.

**Comment by jones137** [comment]
The thing is, I already had all packages you mention installed and it still doesn't work. AppImage should be portable, what's the point of compiling AppImage yourself?

**Comment by a1batross** [comment]
@probonopd @jones137 I would provide it as well, but it may confuse users that just copied a game from Steam release. It will not work, because GoldSource is 32-bit only.

**Comment by jones137** [comment]
So Steam release's "valve" folder will only work if I install it on a 32-bit system?

**Comment by a1batross** [comment]
Yep. As well as Steam itself.

**Comment by probonopd** [comment]
You need to bundle all 32-bit libraries it needs, and a 32-bit ld-linux.so. See https://github.com/probonopd/libhookexecv, there I have done it for a 32-bit Wine to run on 64-bit systems.

**Comment by a1batross** [comment]
And even Mesa drivers? That would give a lot a troubles. Steam already run into it: every major system update breaks Steam Runtime.

Anyway, thanks for pointing it. I will look into this once I'm done with university.

**Comment by mittorn** [comment]
We do not have execve so we do not need in such hooks.
we will not distribute drivers. we'll just wait for proper solution. If vendors drop 32 bit drivers binaries, maybe someone will made some wrapper allowing to use 64bit drivers (using ipc fpr example), or just add libx11 and glx libraries (but glx protocol outdated and even does not support opengles1.1-level graphics, no vbo support).
If ubuntu move to wayland, it will not be possible to make 32 bit gui applications at all (no network transparency)

**Comment by mittorn** [comment]
we even cannot use steam runtime because it does not provide drivers (and break drivers on non-ubuntu). we only need x11 libraries and drivers. we even can link libx11 to SDL2, but nothing to do with drivers. For example, my gpu not supported correctly in opensource drivers, but we cannot bundle amdgpu-pro binaries, it must be downloaded manually
